export interface ManuscriptSection {
  number: string;
  title: string;
  content: string[];
  subsections?: {
    number: string;
    title: string;
    content: string[];
    table?: {
      headers: string[];
      rows: (string | number)[][];
    };
  }[];
}

export const MANUSCRIPT_CONTENT = {
  title: "From Python to Native C++: A Performance Study of Decoder-Only Transformers Using PyTorch and LibTorch",
  subtitle: "An Empirical Study of Training Throughput, Autoregressive Inference Latency, and Memory Footprint on NVIDIA RTX 4090",
  author: "Om Suraj Kashikar",
  institution: "Grade 12, Silver Oaks International School, Hyderabad",
  date: "2026",
  abstract: "This study presents a controlled empirical performance comparison between Python/PyTorch and native C++/LibTorch implementations of a small decoder-only Transformer trained on the TinyStories V2 dataset. Both implementations consume identical pre-tokenized uint16 binary shards produced via the GPT-2 tiktoken tokenizer, enforce a 256-token context length, and implement matched 8-block Pre-LayerNorm Transformer architectures. Training and autoregressive inference were benchmarked on a dedicated NVIDIA GeForce RTX 4090 GPU. The native C++ implementation achieved a sustained training throughput of ~97,500 tokens/sec compared to ~60,000 tokens/sec in Python (a 1.63× advantage / +62.5% speedup), despite Python using CUDA Automatic Mixed Precision (AMP) with GradScaler while C++ executed in full FP32. In autoregressive inference, C++ delivered a median throughput of 190.6 tokens/sec versus 129.0 tokens/sec in Python (+47.8% speedup). Furthermore, C++ reduced inference GPU VRAM allocation by 69.8% (164.8 MB vs. 545.0 MB) and system host RAM by 18.0% (864.7 MB vs. 1,055 MB). Both implementations demonstrated equivalent validation loss trajectories, converging to ~1.41 held-out cross-entropy loss over 100,000 steps (819.2 million tokens).",
  researchQuestion: "How do Python/PyTorch and C++/LibTorch implementations of the same small decoder-only Transformer compare in training throughput, autoregressive inference throughput, and recorded memory use on an NVIDIA RTX 4090?",
  sections: [
    {
      number: "1",
      title: "Introduction & Motivation",
      paragraphs: [
        "Modern deep learning research and deployment rely heavily on high-level Python interfaces such as PyTorch. While PyTorch delegates compute-intensive linear algebra kernels to highly optimized backend libraries (CUDA, cuBLAS, cuDNN), Python itself remains an interpreted language characterized by dynamic typing, reference-counting garbage collection, and the Global Interpreter Lock (GIL).",
        "For high-throughput systems, low-latency edge applications, and resource-constrained environments, host-side overhead—including interpreter dispatch latency, object allocation, and serialization across language boundaries—can introduce tangible bottlenecks. LibTorch, PyTorch's underlying C++ API, provides native access to the ATen tensor library and PyTorch neural network modules without Python runtime dependencies.",
        "This study systematically measures the empirical performance delta between Python/PyTorch and compiled native C++/LibTorch for an end-to-end decoder-only Transformer pipeline, evaluating both sustained training throughput across 100,000 gradient updates and autoregressive token generation on an isolated NVIDIA GeForce RTX 4090 GPU."
      ]
    },
    {
      number: "2",
      title: "Dataset & Preprocessing Pipeline",
      paragraphs: [
        "To eliminate confounding variables stemming from data loading, tokenization discrepancies, or differing data orders, both implementations share an identical preprocessing workflow.",
        "The corpus utilized is TinyStories V2 (Eldan & Li, 2023), consisting of synthetic narratives generated by GPT-3.5 and GPT-4 designed to teach language models coherent English syntax, grammar, and reasoning at compact parameter scales.",
        "Text was preprocessed in Python using OpenAI's tiktoken library with the standard GPT-2 byte-pair encoding (vocabulary size: 50,257). Token streams were pre-tokenized and serialized directly into flat, memory-mappable raw binary files (train.bin and val.bin) containing continuous 16-bit unsigned integers (uint16).",
        "Both the Python training script and the compiled C++ executable stream directly from these identical binary shards. No online tokenization or text parsing occurs during training or evaluation, ensuring zero data drift or token-level discrepancy across the two pipelines."
      ]
    },
    {
      number: "3",
      title: "Transformer Architecture & Mathematical Formulation",
      paragraphs: [
        "The evaluated model is an autoregressive decoder-only Transformer conforming to the Pre-LayerNorm GPT architecture with 8 Transformer blocks and 8 attention heads.",
        "Hyperparameters: Vocabulary size V = 50,257; Context length T = 256; Embedding dimension d_model = 384; Head dimension d_k = 48; MLP hidden width d_ff = 1,536 (4 × d_model); Dropout p = 0.1 applied to attention weights, MLP projections, and residual connections.",
        "Scaled Dot-Product Causal Self-Attention: Each head computes Attention(Q, K, V) = softmax((Q · Kᵀ) / √d_k + M) · V, where M is an upper-triangular causal mask enforcing autoregressive factorization.",
        "Feed-Forward Sublayer: Each block contains a position-wise two-layer network with Gaussian Error Linear Unit (GELU) activation: FFN(x) = GELU(x · W₁ + b₁) · W₂ + b₂.",
        "Weight Tying: In line with modern efficiency practices, the final output linear projection layer shares weight tensors directly with the input token embedding matrix."
      ]
    },
    {
      number: "4",
      title: "Hardware & Software Test Rig",
      paragraphs: [
        "All benchmarks were executed on an isolated cloud host provided by Race Engineering with the following controlled specifications:",
        "GPU: Dedicated NVIDIA GeForce RTX 4090 (24 GB GDDR6X VRAM, Driver 595.99.02, CUDA Toolkit 13.4.0).",
        "C++ Environment: GCC 11.4.0 (flags: -O3 -std=c++17), CMake 3.18, LibTorch 2.5.0 (CUDA-enabled).",
        "Python Environment: Python 3.14 with PyTorch 2.14.0."
      ]
    },
    {
      number: "5",
      title: "Training Methodology & Empirical Throughput",
      paragraphs: [
        "Training Configuration: Optimizer was AdamW (beta1 = 0.9, beta2 = 0.95, eps = 1e-8, weight decay = 0.1). Batch size was fixed at 32 sequences × 256 tokens = 8,192 tokens per parameter update. Total training ran for 100,000 steps (819.2 million total tokens processed). Learning rate followed cosine annealing with 2,000 linear warmup steps (peak lr = 5e-4, min lr = 5e-5).",
        "Precision Setup: Python utilized CUDA Automatic Mixed Precision (torch.cuda.amp.autocast) with GradScaler. C++ LibTorch was executed in full single precision (FP32).",
        "Sustained Training Throughput: Python sustained ~59,000 to 62,000 tokens/sec (midpoint ~60,000 toks/s). Native C++ sustained ~95,000 to 100,000 tokens/sec (midpoint ~97,500 toks/s), yielding a 1.63× speedup (+62.5% advantage) for C++.",
        "Validation Convergence: Evaluated on 200 iterations over held-out val.bin every 10,000 steps. Both implementations tracked each other tightly, converging from ~2.04 at step 10k down to 1.4136 (C++) and 1.4196 (Python) at step 99k, confirming matched algorithmic parity."
      ]
    },
    {
      number: "6",
      title: "Autoregressive Inference & Memory Allocation",
      paragraphs: [
        "Inference Evaluation: Autoregressive decoding was evaluated using the shared prompt 'A small dog found a shiny ball' with temperature = 0.8, top-k = 50, maximum length = 256 tokens, stopping on <|endoftext|>.",
        "Inference Throughput: C++ achieved a median throughput of 190.6 tokens/sec (0.666s latency across 3 runs: 190.6, 190.6, 192.25) vs 129.0 tokens/sec for Python (0.61s latency across 3 runs: 129.0, 123.0, 130.0), a +47.8% speedup (1.48× advantage).",
        "GPU VRAM Footprint: Python allocated 545.0 MB during generation vs C++ allocating only 164.78 MB, representing a 69.8% reduction in GPU memory.",
        "Host RAM Footprint: Python process consumed 1,055 MB vs C++ native process consuming 864.7 MB, an 18.0% system memory reduction."
      ]
    },
    {
      number: "7",
      title: "Systems Analysis & Architectural Discussion",
      paragraphs: [
        "Host-Side Dispatch Overhead: In small-to-medium models, individual CUDA kernel execution times are small (microseconds). The CPython foreign function interface (FFI) and PyTorch dispatch wrapper create host CPU bottlenecks, leading to GPU queue starvation. In native C++, kernel launches proceed without interpreter intervention.",
        "Sequential Decoding Serialization: Autoregressive generation is fundamentally sequential—each token requires a full forward pass. Python repeats interpreter dispatch on every token iteration, compounding overhead over hundreds of sequential steps. C++ executes the loop natively with zero interpreter overhead.",
        "Memory Allocator Lifecycle: Python requires memory for the CPython runtime, loaded dynamic packages, and Python tensor object wrappers. Native C++ maintains a lean memory footprint with zero garbage collection pauses."
      ]
    },
    {
      number: "8",
      title: "Limitations & Threats to Validity",
      paragraphs: [
        "1. Comparison is between Python/PyTorch and C++/LibTorch rather than framework-free custom CUDA kernels.",
        "2. Python training utilized CUDA AMP (mixed precision) with GradScaler, while C++ executed in full FP32. C++ outperforming Python despite FP32 highlights that the host dispatch bottleneck in Python outweighed the compute speedup of mixed-precision tensor cores at this scale.",
        "3. Models were initialized with independent random seeds; while convergence trajectories match closely, individual parameter weights differ.",
        "4. Independent EOT token emission led to varying generated token lengths during stochastic sampling.",
        "5. Inference benchmark is reported across three runs per implementation with median calculation."
      ]
    },
    {
      number: "9",
      title: "Conclusion & Future Directions",
      paragraphs: [
        "This empirical study demonstrates that migrating a decoder-only Transformer pipeline from Python/PyTorch to compiled native C++/LibTorch delivers significant throughput gains (+62.5% in training, +47.8% in autoregressive inference) alongside dramatic reductions in GPU VRAM (-69.8%) and host RAM (-18.0%) on an NVIDIA RTX 4090.",
        "These results illustrate the magnitude of Python interpreter dispatch overhead in small Transformer architectures and substantiate native C++ execution as an effective approach for latency-critical and resource-constrained deployments.",
        "Future directions include integrating custom CUDA FlashAttention kernels, implementing int8/int4 quantization, and evaluating multi-GPU distributed scaling."
      ]
    }
  ]
};
